feat(middleware): add middleware support to framework
serzmerz/frame pull request #3
Opened 2017-04-23 20:52 UTC by serzmerz

2017-04-25 06:28 UTC, Artiomtb requested changes
Поправь замечание с вызовом метода контроллера

2017-04-25 06:28 UTC, Artiomtb commented on src/Application.php
> +                $responsePrepare = $reflectionMethod->invokeArgs($controller, $route->getVariables());
Погоди, у тебя используется заранее заготовленный response ДО вызова всех middleware? Это неверно, response надо получать ПОСЛЕ.

2017-04-25 06:28 UTC, Artiomtb commented on src/Middleware/MiddlewareRunner.php
> +            $nextClosure = $this->buildClosure($value, $lastNext, $this->middlewaresVariables[$key]);
почему сразу не перезаписывать lastNext?

2017-04-26 10:15 UTC, Artiomtb approved these changes
Можно.

2017-04-26 10:16 UTC, merged

2017-05-21 07:52 UTC, ddavidov reviewed
+